poggers
h-exx/h-exx pull request #2
Opened 2020-09-02 16:26 UTC by DamonOnYT

2020-09-02 16:29 UTC, HexDevv requested changes

2020-09-02 16:29 UTC, HexDevv commented on README.md
> +[Xonos](https://xonos.host) - Game and Web hosting company - Support Staff and Developer<br>
i dont work here

2020-09-02 16:29 UTC, HexDevv commented on README.md
> +[Dual](https://dual.pw) - Online Radio Station - Owner<br>
i dont work here

2020-09-02 16:29 UTC, HexDevv commented on README.md
> -[Jinkaku](https://top.gg/bot/706271163168587848) - A discord bot for roleplayers - Owner and Lead Dev<br>
i work here

2020-09-02 16:29 UTC, HexDevv commented on README.md
> -[KeyFM](https://keyfm.net) - An online radio station - Administrator<br>
i work here

2020-09-02 16:29 UTC, HexDevv commented on README.md
> -Music4All - A discord bot which played music. My first ever Discord bot. Shutdown in 2018 - Owner and Lead Dev
i work here

2020-09-02 16:29 UTC, HexDevv commented on README.md
> +[![Github Stats](https://github-readme-stats.vercel.app/api?username=defectivenessyt)]
thats not my github stats

2020-09-02 16:29 UTC, HexDevv commented on README.md
> +I'm Ben, but I'm also known as Defectiveness or benne. I'm 15 and do stupid terrible code in my spare time.
im not ben

2020-09-02 16:32 UTC, DefectivenessYT commented on README.md
> +I'm Ben, but I'm also known as Defectiveness or benne. I'm 15 and do stupid terrible code in my spare time.
but you do terrible code so

2020-09-02 16:56 UTC, HexDevv commented on README.md
> +I'm Ben, but I'm also known as Defectiveness or benne. I'm 15 and do stupid terrible code in my spare time.
> but you do terrible code so

thats true that means im ben

2020-10-20 13:45 UTC, DefectivenessYT commented
RIGHT BOYS I HAVE NO ACCESS TO ANYTHING ELSE BECAUSE IM IN A COMPUTER SCIENCE LESSON AND IM BORED

2020-10-20 14:11 UTC, DefectivenessYT commented
![image](https://user-images.githubusercontent.com/23050115/96598216-8cdcf100-12e6-11eb-8896-668a94e86105.png)

2020-10-20 14:41 UTC, DamonOnYT commented
lol f

2020-11-18 16:07 UTC, HexDevv commented
retard

2020-11-22 13:41 UTC, DefectivenessYT commented on README.md
> +I'm Ben, but I'm also known as Defectiveness or benne. I'm 15 and do stupid terrible code in my spare time.
nigga what

2021-11-09 23:58 UTC, closed without merging